config/routes.rb
Rails.application.routes.draw do

  root to: 'welcome#index'
  get '/about' => 'welcome#about'
  get '/change_year/:new_year' => 'application#change_year', as: 'change_year'

  scope '/:year', defaults: { year: '105' } do
    resources :departments, only: [:index, :show], defaults: { format: 'html' } do
      collection do
        post :search
      end
    end
    get '/' => 'welcome#index'
    get '/colleges/:id' => 'departments#show_college', as: "college"

    get '/get_nodes' => 'departments#get_nodes', defaults: { format: 'json' }
    get '/get_links' => 'departments#get_links', defaults: { format: 'json' }
    get '/force' => 'departments#force'

   resources :ranks, only: [:index, :show], defaults: { format: 'html' }
  end

  
end

app/models/college.rb
class College < ActiveRecord::Base
	self.table_name = "colleges"
	self.primary_key = "college_no"

	has_many :dep_105s
end

app/models/dep.rb
class Dep < ActiveRecord::Base
	self.table_name = "deps"
	self.primary_key = "dep_no", "year"

	def short_name
		self.name.sub(College.find(self.college_no).name, "")
	end

	def last_text
		if self.last > 0
			"正取"
		elsif self.last < 0
			"備取" + (String(self.last.abs) rescue nil)
		else
			"無資料"
		end
	end

	def predict_text
		if self.predict_num.nil?
			"N/A"
		elsif self.predict_num.floor > 0
			"備取" + (String(self.predict_num.floor) rescue nil)
		else
			"正取"
		end
	end

	def field_text
		field_name = {
			0 => "無資料",
			1 => "教育領域",
			2 => "人文及藝術領域",
			3 => "社會科學、商業及法律領域",
			4 => "科學領域",
			5 => "工程、製造及營造領域",
			6 => "農學領域",
			7 => "醫藥衛生及社福領域",
			8 => "服務領域"
		}
		field_name[self.field]
	end

	def lowest_text
		if self.lowest == 0
			"無資料"
		else
			self.lowest
		end
	end

	belongs_to :college
	has_many :winrates
	has_many :links
end

app/models/dep105.rb
class Dep105 < ActiveRecord::Base
	self.table_name = "dep_105"
	self.primary_key = "dep_no"

	def short_name
		self.name.sub(College.find(self.college_no).name, "")
	end

	def last_text
		if self.last > 0
			"正取"
		elsif self.last < 0
			"備取" + (String(self.last.abs) rescue nil)
		else
			"無資料"
		end
	end

	def predict_text
		if self.predict_num.floor > 0
			"備取" + (String(self.predict_num.floor) rescue nil)
		else
			"正取"
		end
	end

	def field_text
		field_name = {
			0 => "無資料",
			1 => "教育領域",
			2 => "人文及藝術領域",
			3 => "社會科學、商業及法律領域",
			4 => "科學領域",
			5 => "工程、製造及營造領域",
			6 => "農學領域",
			7 => "醫藥衛生及社福領域",
			8 => "服務領域"
		}
		field_name[self.field]
	end

	def lowest_text
		if self.lowest == 0
			"無資料"
		else
			self.lowest
		end
	end

	belongs_to :college
	has_many :winrate105s
	has_many :link105s
end

app/models/link.rb
class Link < ActiveRecord::Base
	self.table_name = "links"

	belongs_to :dep
end

app/models/winrate.rb
class Winrate < ActiveRecord::Base
	self.table_name = "winrates"
	# attr_accessor :dep_name
	def dep_name
		Dep.find_by(dep_no: self.dep).name
	end

	def opponent_name
		Dep.find_by(dep_no: self.opponent).name
	end

	def rate_percentage
		self.win_rate * 100
	end

	belongs_to :dep
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

	$available_years = Dep.pluck('year').uniq.sort
	# $available_years = [103, 104, 105]

  def change_year
  	url = request.referrer.split('/')

    #http://domain.name/:year/...
  	url[3] = params[:new_year]
  	url = url.join('/')

	redirect_to url
	rescue ActionController::RedirectBackError
		redirect_to root_path
  end
end

app/controllers/departments_controller.rb
class DepartmentsController < ApplicationController
	before_action :set_year

	def index
		@departments = @dep.all.order(:dep_no)
		@colleges = College.all.order(:college_no)

		respond_to do |format|
			format.html
			format.json { render json: @departments }
		end
	end

	def search
		dep = params[:dep_no]

		redirect_to department_url(dep)
	end

	def show_college
		@college = College.find(params[:id])
		@departments = @dep.where('college_no = (?)', @college.college_no).order(:dep_no)

		rscore_sum = @departments.map(&:ts_rscore).compact.inject(0, &:+)
		rscore_length = @departments.where.not('ts_rscore' => nil).length
		@rscore_mean = rscore_sum / rscore_length
	end

	def show
		@department = @dep.find_by(dep_no: params[:id])

		# for histogram
		rscores = @dep.where.not('ts_rscore' => nil).pluck(:dep_no, :ts_rscore).sort!{|a,b| a[1] <=> b[1]}.reverse
		if rscores.index{|x| x[0] == @department.dep_no}.nil?
			this_rank = "N/A"
			@percentage = "N/A"
		else
			this_rank = rscores.index{|x| x[0] == @department.dep_no} + 1
			@percentage = (((rscores.length - this_rank) / rscores.length.to_f)*100).to_i
		end
		
		
		# for piechart
		@adj_raw = @link.where('source_depno = (?) OR target_depno = (?)', @department.dep_no, @department.dep_no)
		@student_sum = @adj_raw.sum(:value)
		@adj_dep = @adj_raw.map{|r| @department.dep_no == r.source_depno ? { :dep_no => r.target_depno, :name => depNo_to_name(r.target_depno), :value => r.value} : { :dep_no => r.source_depno, :name => depNo_to_name(r.source_depno), :value => r.value} }

		# for win rate
		@win_rate = @winrate.where('dep = (?) AND total >= 5', @department.dep_no)
		@win_rate = @win_rate.sort_by(&:total).reverse
	end

	def get_nodes
		@nodes = @dep.select(:dep_no, :field, :level).order(:dep_no)
		respond_to do |format|
		    format.json { render json: @nodes }
		end
	end

	def get_links
		# @links = File.read('app/assets/javascripts/links105.json')
		@links = @link.where('value >= 5').select(:source, :target, :value)
		respond_to do |format|
		    format.json { render json: @links }
		end
	end

	def force
		@departments = @dep.all.order(:dep_no)

		respond_to do |format|
			format.html
			format.json { render json: @departments }
		end
	end

	def rank
		@fields = {
			0 => "全部領域",
			1 => "教育領域",
			2 => "人文及藝術領域",
			3 => "社會科學、商業及法律領域",
			4 => "科學領域",
			5 => "工程、製造及營造領域",
			6 => "農學領域",
			7 => "醫藥衛生及社福領域",
			8 => "服務領域",
			9 => "其他"
		}
		@this_field = params[:field].to_i
		if @this_field == 0
			@departments = @dep.all.order(:ts_rscore).reverse
		else
			@departments = @dep.where('field = (?)', params[:field]).order(:ts_rscore).reverse
		end
	end

	private

	def set_year
		@year = params[:year]
		@dep = Dep.where('year = (?)', @year)
		@winrate = Winrate.where('year = (?)', @year)
		@link = Link.where('year = (?)', @year)
	end

	def collegeNo_to_name(college_no)
		College.find(college_no).name
	end
	def depNo_to_name(dep_no)
		@dep.find_by(dep_no: dep_no).name
	end
end

app/controllers/rank_controller.rb
class RankController < ApplicationController
	before_action :get_fields

	def index

	end

	def show
		@this_field = params[:id].to_i
		if @this_field == 0
			@departments = Dep105.all.order(:ts_rscore).reverse
		else
			@departments = Dep105.where('field = (?)', @this_field).order(:ts_rscore).reverse
		end
	end

	private

	def get_fields
		@fields = {
			0 => "全部領域",
			1 => "教育領域",
			2 => "人文及藝術領域",
			3 => "社會科學、商業及法律領域",
			4 => "科學領域",
			5 => "工程、製造及營造領域",
			6 => "農學領域",
			7 => "醫藥衛生及社福領域",
			8 => "服務領域",
			9 => "其他"
		}
	end
end

app/controllers/ranks_controller.rb
class RanksController < ApplicationController
	before_action :set_year, :get_fields

	def index
		@departments = @dep.where.not('ts_rscore' => nil).all.order(:ts_rscore).reverse
	end

	def show
		@this_field = params[:id].to_i
		if @this_field == 0
			@with_rscore = @dep.where.not('ts_rscore' => nil).all.order(:ts_rscore).reverse
			@without_rscore = @dep.where('ts_rscore' => nil).all
		else
			@with_rscore = @dep.where('field = (?)', @this_field)
								.where.not('ts_rscore' => nil).all.order(:ts_rscore).reverse
			@without_rscore = @dep.where('field = (?)', @this_field)
									.where('ts_rscore' => nil).all
		end
		@departments = @with_rscore + @without_rscore

		rscore_sum = @departments.map(&:ts_rscore).compact.inject(0, &:+)
		rscore_length = @departments.map(&:ts_rscore).compact.length
		@rscore_mean = rscore_sum / rscore_length
	end

	private

	def set_year
		@year = params[:year]
		@dep = Dep.where('year = (?)', @year)
	end

	def get_fields
		@fields = {
			0 => "全部領域",
			1 => "教育領域",
			2 => "人文及藝術領域",
			3 => "社會科學、商業及法律領域",
			4 => "科學領域",
			5 => "工程、製造及營造領域",
			6 => "農學領域",
			7 => "醫藥衛生及社福領域",
			8 => "服務領域",
			9 => "其他"
		}
	end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
	def index

	end
	def welcome

	end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def title(page_title)
		content_for(:title) { page_title }
	end
end

app/helpers/departments_helper.rb
module DepartmentsHelper
end

app/helpers/ranks_helper.rb
module RanksHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/departments/force.html.erb
<% title "網路圖" %>
<div class="container-fluid" id="network">
	<div class="row">
		<div class="col-md-3" id="sidebar">
			<p id="node_name"><a href="#">　</a></p>
			<div class="block">
				<input type="text" id="search" class="form-control" placeholder="輸入系所名稱">
				<button id="search_submit" class="btn btn-default"><i class="fa fa-search" aria-hidden="true"></i></button>
			</div>
			<div class="block">
				<span>連結閾值</span>
				<div class="range-slider">
					<input id="threshold" type="range" id="thersholdSlider" name="points" class="range-slider__range" value="5" min="5" max="20">
					<span class="range-slider__value">5</span>
				</div>
			</div>

			<div class="block">
				<form id="group">
					<span>分類條件　</span>
					<!-- <input type="radio" name="group" id="cluster" value="cluster" class="form-control">
					<label for="cluster">Cluster</label> -->
					<input type="radio" name="group" id="field" value="field" class="form-control" checked>
					<label for="field">科系領域</label> 
					<input type="radio" name="group" id="level" value="level" class="form-control">
					<label for="level">學校分級</label>
				</form>
			</div>
			
			<div id="legend" class="block">
				<!-- legend inseted here -->
			</div>

			<span class="info">
				<a href="#" data-toggle="modal" data-target="#infoModal">
					<i class="fa fa-question-circle fa-lg" aria-hidden="true"></i>
				</a>
			</span>
		</div>
		<div class="col-md-9">
			<div id="force">
				<h4 id="spinner_text">若載入過久，請重新整理</h4>
			</div>
		</div>
	</div>
</div>

<div id="infoModal" class="modal fade" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">使用說明</h4>
      </div>
      <div class="modal-body">
        <h4>這是什麼？</h4>
		<ul>
			<li>圖中每個點代表一個一間系所，連結代表共同被選取的次數，越粗則次數越多</li>
		</ul>
		<h4>操作說明：</h4>
		<ul>
			<li>搜尋系所會將畫面中心移至該系所，並將點放大</li>
			<li>調整連結的threshold，過濾掉較弱的連結</li>
			<li>調整分群，以不同的指標為系所上色</li>
		</ul>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

app/views/departments/index.html.erb
<% title "系所資料" %>
<div class="container" id="dep_index">
	<div class="row" >
		<div class="col-md-offset-1 col-md-10">
			<div id="search">
				<%= form_tag search_departments_path, :method => :post, :class => 'form-inline' do %>
						<div class="form-group" style="width: 100%;">
							<%= text_field_tag :dep_no, nil, class: "form-control" ,autofocus: true, placeholder: "輸入完整系所名稱" %>
							<button type="submit" class="btn"><i class="fa fa-search" aria-hidden="true"></i></button>
						</div>
				<% end %>
			</div>
		</div>
	</div>

	<div class="row">
	<div style="padding: 0 50px;">
		<% @colleges.each do |c| %>
			<%= link_to college_path(c) do %>
			<div class="col-md-3 one-college">
				<%= c.name %>
			</div>
			<% end %>
		<% end %>
	</div>
	</div>
</div>

app/views/departments/rank.html.erb
<div class="container" id="rank_show">
	<h1><%= @fields[@this_field] %></h1>
	<div class="row">
		<div class="btn-group">
			<button class="btn btn-inverse dropdown-toggle" type="button" data-toggle="dropdown">
		    選擇領域<span class="caret"></span>
			</button>
			<ul class="dropdown-menu dropdown-menu-inverse" role="menu">
		    <% @fields.each_value do |f| %>
				<li><%= link_to f, rank_path(@fields.key(f)) %></li>
		    <% end %>
			</ul>
		</div>
		<table class="table" id="table">
			<thead>
			<tr>
				<th class="sort" data-sort="rank">rank</th>
				<th class="sort" data-sort="name">name</th>
				<th class="sort" data-sort="rscore">Rscore</th>
				<th class="sort" data-sort="mu">mu</th>
				<th class="sort" data-sort="sigma">sigma</th>
				<!-- <th>action</th> -->
			</tr>
			</thead>
			<tbody class="list">
			<% @departments.each_with_index do |d, i| %>
				<tr>
					<td class="rank"><%= i+1 %></td>
					<td class="name"><%= link_to d.name, department_path(d) %></td>
					<td class="rscore"><%= "%.4f" % d.ts_rscore %></td>
					<td class="mu"><%= "%.4f" % d.ts_mu %></td>
					<td class="sigma"><%= "%.4f" % d.ts_sigma %></td>
					<!-- <td>add to graph</td> -->
				</tr>
			<% end %>
			</tbody>
		</table>
	</div>
</div>

app/views/departments/show.html.erb
<% title @department.name %>
<div class="container" id="dep_show">
	<div class="row">
		<h1><%= @department.name %></h1>
	</div>
	<div class="row">
		<div class="col-md-5">
		<div class="panel panel-custom">
			<div class="panel-heading">基本資料</div>
			<div class="panel-body">
				<table class="table no-th">
					<tr>
						<td>正取人數</td>
						<td><%= @department.max_num %></td>
					</tr>
					<tr>
						<td>備取人數</td>
						<td><%= @department.waiting_num %></td>
					</tr>
					<tr>
						<td>實際錄取人數</td>
						<td><%= @department.real_num %></td>
					</tr>
					<tr>
						<td>最低備取名次</td>
						<td><%= @department.last_text %></td>
					</tr>
					<tr>
						<td>預測備取名次</td>
						<td><%= @department.predict_text %></td>
					</tr>
				</table>
			</div>
		</div>
		</div>

		<div class="col-md-7">
		<div class="panel panel-custom">
			<div class="panel-heading">TrueSkill</div>
			<div class="panel-body">
				<div class="col-md-8">
					<div id="histogram">
						<!-- histogram is inserted here -->
					</div>
				</div>
				<div class="col-md-4">
					<table class="table no-th">
					<tr>
						<td>Rscore</td>
						<td><%= @department.ts_rscore.nil? ? "N/A" : "%.2f" % @department.ts_rscore %></td>
					</tr>
					<tr>
						<td>Mu</td>
						<td><%= @department.ts_mu.nil? ? "N/A" : "%.2f" % @department.ts_mu %></td>
					</tr>
					<tr>
						<td>sigma</td>
						<td><%= @department.ts_sigma.nil? ? "N/A" : "%.2f" % @department.ts_sigma %></td>
					</tr>
					<tr>
						<td>百分等級</td>
						<td><%= @percentage %></td>
					</tr>
				</table>
				</div>
			</div>
		</div>
		</div>

		<div class="col-md-6">
		<div class="panel panel-custom">
			<div class="panel-heading">
				交叉分析  
				<a href="#" data-toggle="tooltip" title="圖中之系所代表考生選取本系時，同時選取的系所。若一系所選取之人數不足五人，則會歸類在其他。">
					<i class="fa fa-question-circle fa-lg" aria-hidden="true"></i>
				</a>
			</div>
			<div class="panel-body">
				<div id="piechart">
					<!-- pie chart is inserted here -->
				</div>
			</div>
		</div>
		</div>

		<div class="col-md-6">
		<div class="panel panel-custom">
			<div class="panel-heading">
				對戰紀錄
				<a href="#" data-toggle="tooltip" title="當考生同時有資格錄取本系所與另一系所（即名次皆優於最低備取名次），才會紀錄至總場數中。總場數不足五場之系所不會顯示於下表。">
					<i class="fa fa-question-circle fa-lg" aria-hidden="true"></i>
				</a>
			</div>
			<div class="panel-body">
				<table class="table">
				<thead>
					<tr>
						<th>系所名稱</th>
						<th>勝場</th>
						<th>總場數</th>
						<th>勝率</th>
					</tr>
				</thead>
				<tbody>
				<% @win_rate.each do |w| %>
					<tr>
						<td><%= link_to w.opponent_name, department_path(w.opponent) %></td>
						<td><%= w.win %></td>
						<td><%= w.total %></td>
						<td><%= "%.2f" % w.rate_percentage %> %</td>
					</tr>
				<% end %>
				</tbody>
				</table>
			</div>
		</div>
		</div>

	</div>
	<div class="row">
	
	</div>
</div>

app/views/departments/show_college.html.erb
<% title @college.name %>
<div class="container" id="dep_showcollege">
	<div class="row">
		<div class="col-md-10 col-xs-9">
			<h1><%= @college.name %></h1>
		</div>
		<div class="col-md-2 col-xs-3 title-data">
			<p class="number"><%= "%.2f" % @rscore_mean %></p>
			<p class="description">平均 Rscore</p>
		</div>
	</div>
	<div class="row">
		<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
		<!-- [college]under college name -->
		<ins class="adsbygoogle"
		     style="display:inline-block;width:728px;height:90px"
		     data-ad-client="ca-pub-5123564059378315"
		     data-ad-slot="6439767382"></ins>
		<script>
		(adsbygoogle = window.adsbygoogle || []).push({});
		</script>
	</div>
	<div class="row">
		<% @departments.each do |d| %>
		<div class="col-md-12">
			<%= link_to department_path(d.year, d.dep_no) do %>
			<div class="row one-dep">
				<div class="col-xs-9">
					<span class="name"><%= d.short_name %></span>
				</div>
				<div class="col-xs-1 data">
					<p class="number"><%= d.ts_rscore.nil? ? "N/A" : "%.2f" % d.ts_rscore %></p>
					<p class="description">Rscore</p>
				</div>
				<div class="col-xs-1 data">
					<p class="number"><%= d.ts_mu.nil? ? "N/A" : "%.2f" % d.ts_mu %></p>
					<p class="description">Mu</p>
				</div>
				<div class="col-xs-1 data">
					<p class="number"><%= d.ts_sigma.nil? ? "N/A" : "%.2f" % d.ts_sigma %></p>
					<p class="description">Sigma</p>
				</div>
			</div>
			<% end %>
		</div>
		<% end %>
	</div>
</div>

app/views/layouts/_footer.html.erb
<footer>
	<p id="bottext">© 2016 IMedge</p>
</footer>

app/views/layouts/_navbar.html.erb
<nav  id="navbar" class="navbar navbar-inverse navbar-fixed-top">
<div class="container">
  <div class="row">
    <div class="navbar-header" >
        <%= link_to root_path, class: "navbar-brand" do %>
          <%= image_tag "logo.png" %>
        <% end %>
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#ThisPlaceCollapse">
          <i class="fa fa-bars" aria-hidden="true"></i>
        </button>
    </div>
    <div class="navbar-collapse collapse" id="ThisPlaceCollapse">
        <ul class="nav navbar-nav" >
          <li><%= link_to '系所資料', departments_path %></li>
    			<li><%= link_to '網路圖', force_path %></li>
          <li><%= link_to 'TrueSkill排名', ranks_path %></li>
          <li><%= link_to '關於本站', about_path %></li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
          <li>
            <a href="#" id="navbar_year" class="dropdown-toggle" aria-expanded="true" data-toggle="dropdown">
              選擇年份 <span class="caret"></span>
            </a>
            <ul class="dropdown-menu  dropdown-menu-inverse" role="menu" aria-labelledby="navbar_year">
              <% $available_years.each do |y| %>
                <li><%= link_to y, change_year_path(y) %></li>
              <% end %>
            </ul>
          </li>
        </ul>
    </div>
  </div>
</div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= content_for?(:title) ? yield(:title) : '' %> - 卡利基狂分析</title>

  <%= favicon_link_tag 'logo.ico' %>
  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%= csrf_meta_tags %>
</head>
<body>

	<%= render 'layouts/navbar' %>

	<%= yield %>

	<%= render 'layouts/footer' %>

	<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	<script>
	  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
	  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
	  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
	  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

	  ga('create', 'UA-89793067-1', 'auto');
	  ga('send', 'pageview');
	</script>
</body>
</html>

app/views/ranks/index.html.erb
<% title "TrueSkill排名" %>
<div class="container" id="rank_index">
	<div class="row">
		<div class="col-md-4">
			<div class="fields">
				<% @fields.each_value do |f| %>
					<div class="one-field">
						<fieldset><legend><%= link_to f, rank_path(@fields.key(f)) %></legend>
					</div>
			    <% end %>
			</div>
		</div>
		<div class="col-md-8">
			<div id="boxplot">
				
			</div>
		</div>
	</div>
</div>

app/views/ranks/show.html.erb
<% title @fields[@this_field] %>
<div class="container" id="rank_show">
	<div class="row">
		<div class="col-md-10 col-xs-9">
			<div class="btn-group">
				<button class="btn-title dropdown-toggle" type="button" data-toggle="dropdown">
			    	<h1><%= @fields[@this_field] %> <i class="fa fa-caret-down" aria-hidden="true"></i></h1>
				</button>
				<ul class="dropdown-menu dropdown-menu-inverse" role="menu">
			    <% @fields.each_value do |f| %>
					<li><%= link_to f, rank_path(@fields.key(f)) %></li>
			    <% end %>
				</ul>
			</div>
		</div>
		<div class="col-md-2 col-xs-3 title-data">
			<p class="number"><%= "%.2f" % @rscore_mean %></p>
			<p class="description">平均 Rscore</p>
		</div>
	</div>
	<div class="row">
		<table class="table" id="table">
			<thead>
			<tr>
				<th class="sort" data-sort="rank">rank</th>
				<th class="sort" data-sort="name">name</th>
				<th class="sort" data-sort="rscore">Rscore</th>
				<th class="sort" data-sort="mu">mu</th>
				<th class="sort" data-sort="sigma">sigma</th>
				<!-- <th>action</th> -->
			</tr>
			</thead>
			<tbody class="list">
			<% @departments.each_with_index do |d, i| %>
				<tr>
					<td class="rank"><%= i+1 %></td>
					<td class="name"><%= link_to d.name, department_path(d.year, d.dep_no) %></td>
					<td class="rscore"><%= d.ts_rscore.nil? ? "N/A" : "%.4f" % d.ts_rscore %></td>
					<td class="mu"><%= d.ts_mu.nil? ? "N/A" : "%.4f" % d.ts_mu %></td>
					<td class="sigma"><%= d.ts_sigma.nil? ? "N/A" : "%.4f" % d.ts_sigma %></td>
					<!-- <td>add to graph</td> -->
				</tr>
			<% end %>
			</tbody>
		</table>
	</div>
</div>

app/views/welcome/index.html.erb
<% title "學測科系偏好分析系統" %>
<div class="container-fluid" id="index">
	<div class="row flexbox-center" id="top">
		<div>
			<h1 class="name">學測科系偏好分析系統</h1>
			<br>
			<p class="slogan">不再選錯系，不再變系邊</p>
		</div>
	</div>
	<p class="text-center" style="font-size: 20px; margin: 10px 0;">我們提供</p>
	<br>
	<div class="row">
	<div style="padding: 0 100px;">
		<div class="col-md-4">
		<div class="one-function">
			<h4>詳盡的系所資料</h4>
			<p>所有資料與分析結果優雅的出現，搭配精美的圖表，水啦！</p>
			<%= link_to departments_path, class: "goto" do %>
				前往頁面 <i class="fa fa-chevron-right" aria-hidden="true"></i>
			<% end %>
		</div>
		</div>
		<div class="col-md-4">
		<div class="one-function">
			<h4>酷炫的網路圖</h4>
			<p>系所之間的愛恨情仇一目了然，且提供多項功能，酷啦！</p>
			<%= link_to force_path, class: "goto" do %>
				前往頁面 <i class="fa fa-chevron-right" aria-hidden="true"></i>
			<% end %>
		</div>
		</div>
		<div class="col-md-4">
		<div class="one-function" style="border-right: none;">
			<h4>精準的TrueSkill分數</h4>
			<p>使用與Xbox相同的演算法，馬上決定誰才是老大，準啦！</p>
			<%= link_to ranks_path, class: "goto" do %>
				前往頁面 <i class="fa fa-chevron-right" aria-hidden="true"></i>
			<% end %>
		</div>
		</div>
	</div>
	</div>
</div>